### ISSUE TITLE
The make process does not work on rhel7 or centos7

### ISSUE THREAD

**Issue by chenri** [mikesart/inotify-info#12]
On such a server, you will get the error:

$ make
Using gold linker...
Building _release/inotify-info...
---- inotify-info.cpp ----
g++: error: unrecognized command line option ‘-Wimplicit-fallthrough=2’
make: *** [_release/inotify-info.o] Error 1

The g++ version is

$ g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

Is it possible to update the make process so that it can cover platforms?

Thanks

Richard

**Comment by mikesart** [comment]
We had this [bug 10](https://github.com/mikesart/inotify-info/issues/10) entered previously:

The core issue there, we think, would be this:

> statx() was added to Linux in kernel 4.11; library support was added in glibc 2.28.

and

> the Centos 7 kernel is still 3.10 and glibc on 2.17

So I think we're going to run into more issues than just getting it to compile.

**Comment by mikesart** [comment]
From this chart:
  [distrowatch centos](https://distrowatch.com/table.php?distribution=centos)
It looks to me like we would need CentOS 8.5 or higher to support statx().
