### ISSUE TITLE
tag "releases" occasionally?

### ISSUE THREAD

**Issue by motiejus** [mikesart/inotify-info#23]
Now that [inotify-info starts being included to distros](https://github.com/NixOS/nixpkgs/pull/286538), we (I) may need some "signal' when it' worthwhile to update it downstream.

I could follow all commits and arbitrarily decide when I feel like a "release" is worthy by taking a snapshot.

Or you may think "this is something that should end up downstream" and just cut & push a tag. That has a higher chance to have it consistent across distros, when there are more.

If ut wouldn't be too much to ask, it would be great if you could make a tag from time to time. Distro packagers will do the rest.

Feel free to close it and keep not making tags, I will just keep following the commits.

Thank you for the product!

**Comment by mikesart** [comment]
Adding you as a collaborator. Feel free to tag releases however works for you if you're up for that. Thanks!

**Comment by motiejus** [comment]
I didn' expect that, but thanks!

If you are ok with it, I'll tag 0.1 once the nixos package lands.

Do you use irc or matrix where I could shoot a message before cutting a tag?

**Comment by mikesart** [comment]
Yep, tag away. And, hm. I've switched jobs and mostly we just use Slack here. Also have a discord channel but don't look at that much. Maybe just tag as you see fit and I'll see it with github notifications. If you make any major changes to the code I'd like to take a look, but otherwise please do whatever you need to get your work done and make this useful.

**Comment by motiejus** [comment]
Thanks. I don't plan any changes except an occasional tag. This is an awesome tool as-is. And I am not qualified to review C++ :)

If you find yourself on irc or matrix, my contacts are [here](https://jakstys.lt/contact/).

Good luck with your new job!

**Comment by k0ste** [comment]
@motiejus hi!
What about tags? 😀
Also, it's will good to see a tarballs on releases page

Thanks!
