### ISSUE TITLE
Alignment issues in output

### ISSUE THREAD

**Issue by fatso83** [mikesart/inotify-info#4]
There seems to be some kind of alignment issue when the PID number is only four digits. Furthermore, either the column widths should clip the overflowing text (like on on the lines containing ` (deleted)`) or they should increase the allotted space to allow for the longest length.

![image](https://user-images.githubusercontent.com/618076/199026113-414facbf-5694-40cc-9b30-4496d9e74a86.png)

**Comment by mikesart** [comment]
Should be fixed with commit 5710dd1. Thanks!
