### ISSUE TITLE
Publish the container image to GHCR or Docker Hub

### ISSUE THREAD

**Issue by ejnshtein** [mikesart/inotify-info#41]
I wanted to run this VERY USEFUL tool (THANK YOU) but didn't want to build it. I saw that running a docker container is mentioned in the documentation, so I ran it, but it failed because no image with the name `inotify-info` is available on Docker Hub.
I see a few `<USERNAME>/inotify-info` images on Docker Hub but none from @mikesart account. I ended up running the image from [mongey/inotify-info](https://hub.docker.com/r/mongey/inotify-info) and it worked fine, but still, I want to propose to:
- Publish the image to this repository using GHCR or Docker Hub.
- Update the readme either way with the correct image name, since the current one doesn't work.

Thank you! Awesome tool!

P.S. If you decide to publish a container image to this repo, the command to run it will look like this: `docker run --rm --privileged -v /proc:/proc ghcr.io/mikesart/inotify-info`

**Comment by ejnshtein** [comment]
Just in case, here's a link to documentation on [how to publish images to GHCR](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry).

**Comment by motiejus** [comment]
This was previously discussed in #28.

I have updated the README and clarified the build steps in #43, should be clearer now.
