### ISSUE TITLE
print string error instead of integer errno

### ISSUE THREAD

**Issue by planetrocky** [mikesart/inotify-info#52]
Debugging on my system and had pages of fileio error.
Added simple stderror(errno) to symplify.

**Comment by motiejus** [comment]
Lgtm,

@mikesart, thoughts?

**Comment by mikesart** [comment]
I'm fine with this getting committed. You want to do it @motiejus? For this:

> Debugging on my system and had pages of fileio error

Would love to see what the errors you were getting are, and maybe run something like `lsblk` to see what your filesystem looks like? Thanks.

**Comment by motiejus** [comment]
#54
