### ISSUE TITLE
Support listing inotify watches for flatpak-wrapped apps

### ISSUE THREAD

**Issue by tennox** [mikesart/inotify-info#7]
(note: that it was about flatpaks was only [revealed later on](https://github.com/mikesart/inotify-info/issues/7#issuecomment-1447429132))

`inotify-info 171055`
![image](https://user-images.githubusercontent.com/2084639/219891498-0d0e5b6a-f908-4b42-80b0-9043cab8ec80.png)
&
![image](https://user-images.githubusercontent.com/2084639/219891653-c624f2a5-21e0-4eee-9a85-89308b81e9a1.png)

Running without arguments is fine
![image](https://user-images.githubusercontent.com/2084639/219891806-2d8fc979-5d13-4202-8353-02d45e0ef321.png)

> OS: Fedora release 37 (Thirty Seven) x86_64 
> Host: Framework FRANBMCP0B 
> Kernel: 6.1.11-200.fc37.x86_64 
> Uptime: 7 hours, 10 mins 
> Packages: 3424 (dnf), 12 (nix-user), 43 (nix-default), 79 (flatpak)
> Shell: fish 3.6.0

**Comment by mikesart** [comment]
Can you try the latest with commit 8add69e? Should fix the /proc issues.

For the first case with codium, that process looks like it has 506,980 watches opened. Not sure how to print out all that data without it looking spammy?

**Comment by tennox** [comment]
Oh I did not realize it's supposed to print all IDs or something. A bit unfortunate (don't really care about those) but ok then.
On the latest commit it now behaves better:
![image](https://user-images.githubusercontent.com/2084639/221442830-843595a1-0234-408d-8629-6592c22b6ff5.png)

but the info is a bit less useful than I had hoped - I thought there was a way to know which files are being watches :cry: 

Anyways, I guess this solves the issue at hand (albeit not my issue of trying to find out why it has these friggin 500000 watches). You happen to have an idea for that?

Thanks in any case :handshake:

**Comment by mikesart** [comment]
If things are working the way they're supposed to :), it should spit out the filenames at the bottom if you specify a PID or appname to search for. Like this:

![image](https://user-images.githubusercontent.com/1740476/221449559-f9801432-06ad-4616-a902-3a343502e629.png)

**Comment by mikesart** [comment]
Those numbers in gray and green are inodes and the [259.5] shows what device it's under. So for mine above, it's my nvme0n1p2:

![image](https://user-images.githubusercontent.com/1740476/221449750-5f5121f6-b4fd-4067-9b73-d47f3b66a246.png)

**Comment by mikesart** [comment]
Yours says [0.32] and [0.25]. Can you see what those are on your system? Also, if it's an ext4 filesystem you should be able to do something like this to find the inode as well:

sudo debugfs -R 'ncheck 14550430' /dev/nvme0n1p2 2>/dev/null

**Comment by mikesart** [comment]
I'm going to re-open this cause I'm curious what's going on with your system... :)

**Comment by mikesart** [comment]
Are you running codium via a snap or something? And yeah... I have no idea what's going on here!

**Comment by tennox** [comment]
In a flatpak, fair point that's probably it :sweat_smile: 

Ran a simple `inotifywait -rm (mktmp -d)`
and your tool seem to work fine :+1: 
![image](https://user-images.githubusercontent.com/2084639/221729519-a78298af-85fa-45a9-87b0-dd05a7f95138.png)

Supporting flatpaks is probably out of scope?

**Comment by mikesart** [comment]
If you can find anyone with suggestions on how to do this I could try to code it up, but otherwise it very likely isn't going to happen. Sorry! And I'll close this out... thanks for the help.
